---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint-docker
        args:
          - "--ignore"
          - terraform
          - "--fix"

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.0
    hooks:
      - id: golangci-lint-full
        entry: "bash -c 'cd collector'"

  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.7.8
    hooks:
      - id: actionlint-docker

  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your repo
        entry: bash -c '.github/bin/trufflehog'
        language: system
        stages: ["pre-commit", "pre-push"]
