---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/zahorniak/pre-commit-circleci.git
    rev: v1.1.0
    hooks:
      - id: circleci_validate
        args:
          - --org-id=da607531-93bb-4321-90ed-08710434ce1c

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.23
    hooks:
      - id: trufflehog

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-docker
        args:
          - "--ignore"
          - terraform
          - "--fix"

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.0.2
    hooks:
      - id: golangci-lint-full
        entry: "bash -c 'cd collector'"
