frameworkVersion: "3"
service: fpo-model-garbage-collection

provider:
  name: aws
  region: eu-west-2
  runtime: provided.al2023
  stage: ${env:STAGE}
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
  environment:
    DRY_RUN: ${env:DRY_RUN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::${env:MODEL_BUCKET}"
        - "arn:aws:s3:::${env:MODEL_BUCKET}/*"

    - Effect: "Allow"
      Action:
        - kms:GenerateDataKey
        - kms:Decrypt
      Resource:
        - "arn:aws:kms:${self:provider.region}:${aws:accountId}:key/*"

package:
  patterns:
    - bootstrap

functions:
  collector:
    handler: bootstrap
    events:
      - schedule: cron(0 12 * * ? *) # Run every day at 12 PM
